### ISSUE TITLE
Add vue.js to javascript frameworks

### ISSUE THREAD

**Issue by icebob** [sahat/megaboilerplate#101]
http://vuejs.org/

**Comment by sahat** [comment]
HI @icebob,

Putting the time it takes to learn Vue.js aisde, plus writing a generator for it, just to give you an idea here is how many modules there are to generate a React app in Mega Boilerplate:

<img width="466" alt="screenshot 2016-06-09 14 17 54" src="https://cloud.githubusercontent.com/assets/544954/15941271/54746ece-2e4d-11e6-92eb-765d54d58cb5.png">
<img width="470" alt="screenshot 2016-06-09 14 17 42" src="https://cloud.githubusercontent.com/assets/544954/15941272/54757dfa-2e4d-11e6-9344-9c75c1b6c560.png">
<img width="466" alt="screenshot 2016-06-09 14 17 33" src="https://cloud.githubusercontent.com/assets/544954/15941269/547121d8-2e4d-11e6-82a4-144141e05c85.png">
<img width="469" alt="screenshot 2016-06-09 14 17 24" src="https://cloud.githubusercontent.com/assets/544954/15941270/5471a40a-2e4d-11e6-90bb-70a5fe684288.png">

Adding a new JavaScript framework is no small task.

**Comment by icebob** [comment]
Ok, I think. It was an idea. Maybe a vuejs master make it :)

**Comment by sahat** [comment]
I ran a quick survey but there doesn't seem to be much interest for Vue.js relatively speaking. Going to close this issue. If enough people are interested in Vue.js I will consider accepting a PR.

<img width="520" alt="screen shot 2016-06-13 at 6 39 40 pm" src="https://cloud.githubusercontent.com/assets/544954/16049633/768f7044-3226-11e6-97a5-e7d82ddd84fa.png">

**Comment by estevanmaito** [comment]
Hey @sahat!

I've been using megaboilerplate without a JS framework since it's first release, and would like to help you adding Vue to it.

As I can see, there's a lot of work to be done, but that's not the biggest challenge for me here. I can't find any contributing guideline (I've already made a PR some time ago, but at the time it wasn't a big piece of code) so, would you mind giving me some details of what need to be done, if I should work and commit to a branch before pulling to master, and so on?

Thank you.

**Comment by mylastore** [comment]
@estevanmaito did you get a respond on adding vue?

**Comment by digitalit** [comment]
+1 for Vue

**Comment by raouftiliouine** [comment]
+1 Vue would be a fantastic addition to the boilerplate.
