### ISSUE TITLE
Add koa.js to javascript frameworks

### ISSUE THREAD

**Issue by rgaidot** [sahat/megaboilerplate#103]

**Comment by stondo** [comment]
+1

**Comment by sahat** [comment]
I know this is a small sample size, but based on my mini survey, there wasn't enough interest for Koa. Adding a new framework would take an immense amount of effort due to subsequent generators conditionally generate code based on the framework (just Express for now), that's why I ended up removing Hapi as one of the choices.

<img width="557" alt="screen shot 2016-06-09 at 9 59 38 pm" src="https://cloud.githubusercontent.com/assets/544954/15952341/e182b45c-2e8d-11e6-937a-bc87b3f1c88c.png">
