### ISSUE TITLE
NW.js support

### ISSUE THREAD

**Issue by TheJaredWilcurt** [sahat/megaboilerplate#124]
I see Electron support is being added. It's a little disappointing that it's getting support before NW.js, since it's just a bad knockoff of it.

* NW.js has been around 5 years longer
* Is more stable
* Has better documentation
* Is updated faster (within 24 hours of each new Chromium or Node release)
* Supports more OS's (XP+, OSX 10.6+, Ubuntu/Zorin/Debian)
* Wayyyyyyy easier [to get started with](http://thejaredwilcurt.github.io/website/quickstart.html)
* Common sense coding. (You can actually include jQuery like you normally would instead of having to require it in via Node in some backwards way)
* It's ready out of the box, you don't need to create a JS file to then create a window to then create a close button that works. You just start with a Native Window with all the defaults and can opt out if you don't want them (more common sense).

Outside of a bad logo and horrendously bad name, NW.js is better in every way to Electron.

**Comment by sahat** [comment]
Hi @TheJaredWilcurt,

Thanks for the feedback! I am more familiar with Electron right now, which is why I am planning to add it first.

I would be happy to accept any pull requests you might have to add NW.js support, and I will keep in mind your feedback when deciding what future frameworks to add.
