### ISSUE TITLE
gulp wont run beacuse of gulp.series function is not defined

### ISSUE THREAD

**Issue by rickbrunstedt** [sahat/megaboilerplate#130]
The boilerplate gives me gulp version 3.9.1, and if I'm correct that doesn't support gulp.series, right?
It complains about that anyway, it's undefined..

Then I installed gulp 4 and tried, in that case it complains again and says "AssertionError: Task function must be specified"

Then had to change 
this -> gulp.task('default', ['build', 'watch']);
to that -> gulp.task('default', gulp.series('build', 'watch'));

Correct me if I'm wrong, but isn't the first one the gulp 3 way of doing it, and then gulp.series() is gulp 4 way of doing it?

Which version is this made for?
Am I missing something?

**Comment by sahat** [comment]
I started initially with gulp 4, but since it's not even out yet I have decided to switch back to gulp 3.9. If there are gulp.series leftover modules, that's a bug and needs to be fixed.

**Comment by rickbrunstedt** [comment]
Alright! I Probably have time later to make a pr.

At the moment I had some problem with "ng-annotate" to run. The problem was that the first line in "app.js" had "<%= satellizer %>", I changed it to "sattellizer" and it worked.

Is there a reason it said "<%= satellizer %>" ? I guess that is a variable, if so, there does it come from?

Maybe off topic, but the reason I asking, I saw that you owned that repo as well. 😄 
And it could help me make an pr.

**Comment by sahat** [comment]
@rickbrunstedt That's also a bug, although strangely enough, I haven't encountered it during testing. Basically, it's a string placeholder. If you have selected any Authentication checkboxes, "satellizer" string will be added to app module dependencies, otherwise it should be replaced with an empty string, i.e. "<%= satellizer %>" should go away regardless.

And you are right it's one of the angular modules I built two years ago for easier authentication process in AngularJS apps.
