### ISSUE TITLE
Missing js directory for build

### ISSUE THREAD

**Issue by valours** [sahat/megaboilerplate#137]
build : 
 - node
 - express (with pm2 and socket.io)
 - Handlebars
 - no css
 - react (devtools)
 - npm
 - mocha
 - no db

with this configuration, i have a trouble when I build the app with 'npm run build'. The solution is to create manually missing folder '/public/js'.

Regards

**Comment by sahat** [comment]
I can reproduce the problem. The issue is that `browserify` command is not recursively creating sub-directories. If browserify doesn't have a flag to do it, one approach would be to create an empty `js` directory with `.gitkeep` file inside so that `js` folder is always present - in local and production environments.
