### ISSUE TITLE
Azure Publish Error - bundle.js

### ISSUE THREAD

**Issue by MobileAppVault** [sahat/megaboilerplate#138]
Hi,

I've published my app to azure app service like it described in the documentation.

I've also setup all environment parameters in the "application settings" section on azure portal

> NODE_EV: production
> TOKEN_SECRET: xxxx
> MONGODB: mongo://xxxxx

When I open my web app I am not able to login into the app. I know there can be a issue with the mongodb connection but the strange thing is that I get no server message response in my web app when I leave the sign up fields empty. It should show me the messages "Name cannot be blank" and so on.

I've tried to find out if the service for login available and yes it is avail when I request it via postman.

POST/ http://boiler-with-db.azurewebsites.net/login
```
[
  {
    "param": "email",
    "msg": "Email is not valid"
  },
  {
    "param": "email",
    "msg": "Email cannot be blank"
  },
  {
    "param": "password",
    "msg": "Password cannot be blank"
  }
]
```
What I also observed is an error in the developer console:

`bundle.js:1 Uncaught SyntaxError: Unexpected token <`

`Failed to parse SourceMap: http://boiler-with-db.azurewebsites.net/css/vendor/bootstrap.css.map`

It looks like the bundle.js is empty and only included the 404 page code.

Can anybody help me with that issue?

> **my configuration:** 
> Platform: node
> Framework: express
> Template Engine: jade
> CSS Framework: bootstrap
> CSS Preprocessor: css
> JavaScript Framework: react
> Build Tool: webpack
> Unit Testing: none
> Database: MongoDB
> Authentication: email, facebook, twitter, google
> Deployment: azure

**Comment by sahat** [comment]
I suspect you are having the same issue that I had with megaboilerplate site when it was hosted on Azure. 

The reason why you are getting `bundle.js:1 Uncaught SyntaxError: Unexpected token <` is because it cannot find `bundle.js` file. It cannot find it because the file is never being generated on Azure.

I'll take a look at the azure deployment script again, but meanwhile you should compile bundle.js locally via npm run build and commit it to Git.

**Comment by MobileAppVault** [comment]
Many thanks for your help. Will do it like you described!
